apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-backend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-migrations-job-read
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    resourceNames: ["{{ .Release.Name }}-migrations-{{ .Release.Revision }}"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-migrations-job-read
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-migrations-job-read
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-backend
