apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
spec:
  revisionHistoryLimit: 0
  replicas: 4
  selector:
    matchLabels:
      app: {{ .Release.Name }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-frontend
    spec:
      containers:
        - name: main
          image: ghcr.io/ondrejsika/counter-frontend
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: API_ORIGIN
              value: http://{{ .Release.Name }}-backend
            - name: FONT_COLOR
              value: "white"
            - name: BACKGROUND_COLOR
              value: "black"
          livenessProbe:
            httpGet:
              path: /api/livez
              port: http
          startupProbe:
            httpGet:
              path: /api/livez
              port: http
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              cpu: 500m
              memory: 500Mi
